# OpenAPI definition of the lab notebook API
#
# Copyright (C) 2023 Simon Dobson
#
# This file is part of cloud-epydemic, network simulation as a service
#
# cloud-epydemic is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published byf
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cloud-epydemic is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cloud-epydemic. If not, see
#<http://www.gnu.org/licenses/gpl.html>.

openapi: 3.0.3
info:
  title: "cloud-epydemic lab notebook API"
  description: "A microservices interface to cloud-based lab notebooks"
  version: "0.1.0"

servers:
  - url: "/api/v1"

components:
  schemas:
    ResultSet:
      description: "The name and (optional description) of a result set"
      type: "object"
      required:
        - "tag"
      properties:
        tag:
          type: "string"
        description:
          type: "string"

    ResultsDict:
      description: "A results dict"
      type: "object"
      required:
        - "parameters"
        - "metadata"
        - "results"
      properties:
        parameters:
          type: "object"
        metadata:
          type: "object"
        results:
          type: "object"

    ResultsDictAndSet:
      description: "A results dict and optional result set"
      type: "object"
      required:
        - "results"
      properties:
        resultset:
          type: "string"
        results:
          $ref: "#/components/schemas/ResultsDict"

paths:
  /addResultSet:
    post:
      description: "Add a new result set to the lab notebook"
      operationId: "micro_labnotebook.labnotebook.addResultSet"
      tags:
        - "Result sets"
      requestBody:
        description: "Result set to add"
        required: True
        x-body-name: "rsdesc"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResultSet"
      responses:
        200:
          description: "Result set created"

  /addResult:
    post:
      description: "Add new results to the lab notebook"
      operationId: "micro_labnotebook.labnotebook.addResult"
      tags:
        - "Results"
      requestBody:
        description: "Result to add"
        required: True
        x-body-name: "rsrc"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResultsDictAndSet"
      responses:
        200:
          description: "Results added"
